### ISSUE TITLE
sql errors

### ISSUE THREAD

**Issue by CprlRst** [craftyshaun/whmcs-grouppay#12]
i have installed and get the following error 

Deprecated: mysql_escape_string(): This function is deprecated; use mysql_real_escape_string() instead. in /home/vivahost/public_html/my/modules/addons/group_pay/functions_hash.php on line 63

**Comment by JHulsmans** [comment]
Alright this might be a really late response but for completion. Did you get this solved? If not could you give us the MySQL version you're running since it's running just fine on the latest. (last time I checked.)

**Comment by craftyshaun** [comment]
Closing Issue - No Reposnse - Please try latest version.
