### ISSUE TITLE
Client area link is gone

### ISSUE THREAD

**Issue by dimitrifrom31** [craftyshaun/whmcs-grouppay#14]
From an active client point of view, the link to find the group pay hash/link to provide to contributors is missing from the client area.

**Comment by dimitrifrom31** [comment]
the following hook is fixing the issue adding a Group Pay link at the end of the "Billing" menu in client area:

`<?php
 
use WHMCS\View\Menu\Item as MenuItem;
 
add_hook('ClientAreaPrimaryNavbar', 1, function (MenuItem $primaryNavbar)
{
    if (!is_null($primaryNavbar->getChild('Billing'))) {
        $primaryNavbar->getChild('Billing')
            ->addChild('Group Pay', array(
                'label' => 'Group Pay',
                'uri' => 'grouppay.php',
                'order' => '100',
            ));
    }
});`

**Comment by craftyshaun** [comment]
PR Merged to Fix issue.
